services:
  - type: web
    name: mypurewaterbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: WEBHOOK_MODE
        value: true
      - key: WEBHOOK_PATH
        value: /webhook
